// Static Web App for the PWA listener.
// Standard tier: needed for the SWA-managed API function (/api/share → DirectLine).
param location string
param tags object

resource swa 'Microsoft.Web/staticSites@2024-04-01' = {
  name: 'swa-echo-listener'
  location: location
  tags: tags
  sku: {
    name: 'Standard'
    tier: 'Standard'
  }
  properties: {
    // Repo is wired via GitHub Actions deployment token after creation
    // (the token is generated by SWA on first deploy)
    provider: 'None'
    allowConfigFileUpdates: true
  }
}

output defaultHostName string = swa.properties.defaultHostname
output staticWebAppId string = swa.id
output deploymentTokenName string = '${swa.name}-deployment-token'
